# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8240184812d4dde257f7b64c8f7b7802c9e297c83118f3f2ed31e2ca0cfcf2cb273e0f059fd7a0756926c28ce11ff9938c9829a1ec3282a5cd4e0f8d027e2ae

test:
  secret_key_base: 21a2561fef6ce1a11b345e421f2d3f8539c8d664a50c075a55e1812b629e98dea5d8b960a3acad23a13d2e98fa5d07c857d43bc9cc06d8c4a53cc4e36afc8c95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
